Repository HUSTLE-UMC/HUSTLE_server, pull requests merged in 2023-08, with the labels that each got.

#32 [Feat/#27] 동아리 엔티티 생성
  src/main/java/com/sporthustle/hustle/src/club/entity/Club.java
  src/main/java/com/sporthustle/hustle/src/sportposition/entity/SportPosition.java
Labels: feat

#22 [Feat/#19] 아이디/비밀번호 찾기
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
  src/main/java/com/sporthustle/hustle/src/user/UserController.java
  src/main/java/com/sporthustle/hustle/src/user/UserDetailService.java
  src/main/java/com/sporthustle/hustle/src/user/UserRepository.java
  src/main/java/com/sporthustle/hustle/src/user/UserService.java
  src/main/java/com/sporthustle/hustle/src/user/entity/User.java
  src/main/java/com/sporthustle/hustle/src/user/model/FindAccountReq.java
  src/main/java/com/sporthustle/hustle/src/user/model/FindAccountRes.java
  src/main/java/com/sporthustle/hustle/src/user/model/FindEmailReq.java
  src/main/java/com/sporthustle/hustle/src/user/model/FindEmailRes.java
  src/main/java/com/sporthustle/hustle/src/user/model/ResetPasswordReq.java
  src/main/java/com/sporthustle/hustle/src/user/model/ResetPasswordRes.java
Labels: feat

#35 [Feat/#34] 토큰을 통한 이메일 추출
  src/main/java/com/sporthustle/hustle/common/config/SwaggerConfig.java
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityUtils.java
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/src/TestController.java
Labels: feat

#40 [Fix/#39] 회원가입 시 대학 입력 누락 수정
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/src/university/UniversityRepository.java
  src/main/java/com/sporthustle/hustle/src/user/UserService.java
  src/main/java/com/sporthustle/hustle/src/user/entity/User.java
  src/main/java/com/sporthustle/hustle/src/user/model/JoinReq.java
Labels: fix

#42 [Feat] 개인정보 수정 api 구현
  src/main/java/com/sporthustle/hustle/src/user/UserController.java
  src/main/java/com/sporthustle/hustle/src/user/UserService.java
  src/main/java/com/sporthustle/hustle/src/user/entity/User.java
  src/main/java/com/sporthustle/hustle/src/user/model/ModifyUserInfoReq.java
  src/main/java/com/sporthustle/hustle/src/user/model/ModifyUserInfoRes.java
Labels: feat

#45 [Fix/#44] 회원 정보 수정 api 에서 비밀번호 수정 삭제
  src/main/java/com/sporthustle/hustle/src/user/UserService.java
  src/main/java/com/sporthustle/hustle/src/user/entity/User.java
  src/main/java/com/sporthustle/hustle/src/user/model/ModifyUserInfoReq.java
Labels: fix

#46 [Feat/#43] 회원 정보 수정을 위한 회원 정보 조회
  src/main/java/com/sporthustle/hustle/src/user/UserController.java
  src/main/java/com/sporthustle/hustle/src/user/UserService.java
  src/main/java/com/sporthustle/hustle/src/user/model/GetUserInformationRes.java
Labels: feat

#51 [Refactor] `CompetitionService` 리팩터링
  src/main/java/com/sporthustle/hustle/competition/CompetitionService.java
Labels: refactoring

#52 [Refactor] `CompetitionService` 코드에 스웨거 어노테이션 삭제
  src/main/java/com/sporthustle/hustle/competition/CompetitionService.java
Labels: refactoring

#54 [Bug] 스웨거에 `https` 프로토콜을 대응하기 위한 버그 수정
  build.gradle
  src/main/java/com/sporthustle/hustle/common/config/SwaggerConfig.java
Labels: bug

#56 [Feature] 릴리즈 노트 초안 작성해주는 Github actions 설정 / 스크립트 추가
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: feat

#57 [Feature] HOT 대회 목록 조회 API 작성
  src/main/java/com/sporthustle/hustle/competition/CompetitionController.java
  src/main/java/com/sporthustle/hustle/competition/CompetitionService.java
  src/main/java/com/sporthustle/hustle/competition/dto/CompetitionResponseDTO.java
  src/main/java/com/sporthustle/hustle/competition/repository/CompetitionRepositoryCustom.java
Labels: feat

#58 [Feature] Gradle CI 스크립트를 추가
  .github/workflows/gradle-ci.yml
  src/test/resources/application.yml
Labels: feat

#66 [Feature] 대회 세부 정보 도메인 작성
  src/main/java/com/sporthustle/hustle/common/config/WebConfig.java
  src/main/java/com/sporthustle/hustle/common/converter/CompetitionTypeRequestConverter.java
  src/main/java/com/sporthustle/hustle/common/converter/InGameTypeRequestConverter.java
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/competitions/competition/CompetitionController.java
  src/main/java/com/sporthustle/hustle/competitions/competition/CompetitionService.java
  src/main/java/com/sporthustle/hustle/competitions/competition/repository/CompetitionRepositoryCustom.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamController.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamService.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/dto/CreateEntryTeamRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/dto/CreateEntryTeamResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/dto/DeleteEntryTeamResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/dto/EntryTeamResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/dto/EntryTeamsResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/entity/EntryTeam.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/repository/EntryTeamRepository.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/CompetitionDetailController.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/CompetitionDetailService.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/CompetitionDetailUtils.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/dto/DetailResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/dto/InGameType.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/dto/UpdateDetailRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/dto/UpdateDetailResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/entity/FinalRoundDetail.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/entity/FinalRoundTeam.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/entity/PreRoundDetail.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/entity/PreRoundGroup.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/repository/FinalRoundDetailRepository.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/repository/PreRoundDetailRepository.java
  src/main/java/com/sporthustle/hustle/competitions/match/entity/MatchResultPost.java
Labels: feat

#68 [Feat/#67] 스웨거 - 프론트엔드 로컬 서버 추가
  src/main/java/com/sporthustle/hustle/common/config/SwaggerConfig.java
Labels: feat

#72 [Fix/#71] CORS 해결을 위한 출처 허용
  src/main/java/com/sporthustle/hustle/common/config/WebConfig.java
Labels: bug

#74 [Fix/#73] cors 해결 코드에 대한 보안 이슈 해결
  src/main/java/com/sporthustle/hustle/common/config/WebConfig.java
Labels: bug

#76 [Fix/#75] swagger buildproperties bean 에러 해결
  src/main/java/com/sporthustle/hustle/common/config/BuildConfig.java
Labels: bug

#78 [Fix/#77] 스웨거 시큐리티 설정 수정
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
Labels: bug, fix

#81 [Fix/#80] 스웨거 403에러 해결
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
Labels: fix

#85 [HotFix] Swagger 에서 CORS 오류로 GET 외의 요청이 가지 않는 오류 해결
  src/main/java/com/sporthustle/hustle/common/config/WebConfig.java
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
  src/main/java/com/sporthustle/hustle/common/consts/Constants.java
Labels: bug

#88 [Fix/#87] 동아리 가입 api 포지션 제거
  src/main/java/com/sporthustle/hustle/club/ClubController.java
  src/main/java/com/sporthustle/hustle/club/entity/ClubMember.java
  src/main/java/com/sporthustle/hustle/sport/entity/SportEvent.java
  src/main/java/com/sporthustle/hustle/sport/entity/SportPosition.java
Labels: fix

#70 [Feat/#33] 카카오 소셜 로그인
  build.gradle
  src/main/java/com/sporthustle/hustle/auth/AuthController.java
  src/main/java/com/sporthustle/hustle/auth/AuthService.java
  src/main/java/com/sporthustle/hustle/auth/dto/oauth/OAuthSignInRequestDTO.java
  src/main/java/com/sporthustle/hustle/auth/dto/oauth/OAuthSignInResponseDTO.java
  src/main/java/com/sporthustle/hustle/auth/dto/oauth/OAuthSignUpRequestDTO.java
  src/main/java/com/sporthustle/hustle/auth/dto/oauth/OAuthSignUpResponseDTO.java
  src/main/java/com/sporthustle/hustle/common/config/SwaggerConfig.java
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
  src/main/java/com/sporthustle/hustle/common/consts/Constants.java
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/common/jwt/dto/KakaoTokenInfo.java
  src/main/java/com/sporthustle/hustle/oauth/OAuthController.java
  src/main/java/com/sporthustle/hustle/oauth/OAuthService.java
  src/main/java/com/sporthustle/hustle/oauth/dto/OAuthUserInfoResponseDTO.java
  src/main/java/com/sporthustle/hustle/oauth/utils/OAuthConnector.java
  src/main/java/com/sporthustle/hustle/oauth/utils/kakao/KakaoInformationParser.java
  src/main/java/com/sporthustle/hustle/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: feat

#84 [Feat/#18] s3 파일 업로드
  build.gradle
  src/main/java/com/sporthustle/hustle/common/config/S3Config.java
  src/main/java/com/sporthustle/hustle/common/config/security/SecurityConfig.java
  src/main/java/com/sporthustle/hustle/infra/s3/S3Controller.java
  src/main/java/com/sporthustle/hustle/infra/s3/S3Service.java
  src/main/java/com/sporthustle/hustle/infra/s3/dto/S3UploadResponseDTO.java
  src/main/resources/application.yml
Labels: feat

#89 [Feat/#41] 교류전 api 구현
  build.gradle
  src/main/java/com/sporthustle/hustle/common/config/JacksonConfig.java
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/friendmatch/FriendMatchController.java
  src/main/java/com/sporthustle/hustle/friendmatch/FriendMatchingController.java
  src/main/java/com/sporthustle/hustle/friendmatch/FriendMatchingService.java
  src/main/java/com/sporthustle/hustle/friendmatch/FriendMatchingUtils.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingpost/CreateFriendMatchingPostRequestDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingpost/CreateFriendMatchingPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingpost/FriendMatchingPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingrequest/CreateFriendMatchingRequestRequestDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingrequest/CreateFriendMatchingRequestResponseDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingrequest/FriendMatchingRequestResponseDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingrequest/FriendMatchingRequestsResponseDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingrequest/UpdateFriendMatchingRequestStateRequestDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/dto/friendmatchingrequest/UpdateFriendMatchingRequestStateResponseDTO.java
  src/main/java/com/sporthustle/hustle/friendmatch/entity/FriendMatchingPost.java
  src/main/java/com/sporthustle/hustle/friendmatch/entity/FriendMatchingRequest.java
  src/main/java/com/sporthustle/hustle/friendmatch/repository/FriendMatchingPostRepository.java
  src/main/java/com/sporthustle/hustle/friendmatch/repository/FriendMatchingRequestRepository.java
  src/main/java/com/sporthustle/hustle/user/dto/FriendMatchingUserResponseDTO.java
  src/main/resources/application.yml
Labels: feat

#90 [Feature/#65] 대회 매치 결과 CRUD 작성
  src/main/java/com/sporthustle/hustle/common/converter/InGameTypeRequestConverter.java
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/competitions/competition/entity/Competition.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamController.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamService.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/InGameController.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/InGameService.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/dto/InGameCategory.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/dto/InGameType.java
  src/main/java/com/sporthustle/hustle/competitions/match/MatchController.java
  src/main/java/com/sporthustle/hustle/competitions/match/MatchService.java
  src/main/java/com/sporthustle/hustle/competitions/match/MatchUtils.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/CreateMatchResultPostRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/CreateMatchResultPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/CreateMatchResultPostScoreLogRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/DeleteMatchResultPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/MatchResultPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/MatchResultPostScoreLogResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/MatchResultPostsResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/UpdateMatchResultPostRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/UpdateMatchResultPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/UpdateMatchResultPostScoreLogRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/entity/MatchResultPost.java
  src/main/java/com/sporthustle/hustle/competitions/match/entity/MatchResultPostCategory.java
  src/main/java/com/sporthustle/hustle/competitions/match/entity/MatchResultPostScoreLog.java
  src/main/java/com/sporthustle/hustle/competitions/match/repository/MatchResultPostRepository.java
  src/main/java/com/sporthustle/hustle/competitions/match/repository/MatchResultPostRepositoryCustom.java
  src/main/java/com/sporthustle/hustle/competitions/match/repository/MatchResultPostScoreLogRepository.java
  src/main/java/com/sporthustle/hustle/competitions/match/repository/condition/GetMatchResultPostsCondition.java
Labels: feat

#94 [Fix/#93] 카카오 로그인 secret 정보 수정
  src/main/java/com/sporthustle/hustle/oauth/OAuthService.java
  src/main/resources/application.yml
Labels: fix

#95 [Refactor] 파일 업로드 로직 리팩터링
  build.gradle
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/common/exception/FileUploadExceptionHandler.java
  src/main/java/com/sporthustle/hustle/infra/s3/S3Controller.java
  src/main/java/com/sporthustle/hustle/infra/s3/S3Service.java
  src/main/java/com/sporthustle/hustle/infra/s3/dto/S3UploadResponseDTO.java
  src/main/resources/application.yml
Labels: refactoring

#96 [Refactor/#92] 대회 경기 일정으로 대회 매치 결과 & 예선 그룹 생성 로직 수정
  src/main/java/com/sporthustle/hustle/common/exception/ErrorCode.java
  src/main/java/com/sporthustle/hustle/competitions/competition/dto/CompetitionState.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamController.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamService.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/EntryTeamUtils.java
  src/main/java/com/sporthustle/hustle/competitions/entryteam/repository/EntryTeamRepository.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/InGameService.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/InGameUtils.java
  src/main/java/com/sporthustle/hustle/competitions/ingame/repository/PreRoundGroupRepository.java
  src/main/java/com/sporthustle/hustle/competitions/match/MatchController.java
  src/main/java/com/sporthustle/hustle/competitions/match/MatchService.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/CreateMatchRequestPostsRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/CreateMatchResultPostRequestDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/dto/CreateMatchResultPostResponseDTO.java
  src/main/java/com/sporthustle/hustle/competitions/match/repository/MatchResultPostRepository.java
Labels: feat, refactoring

#98 [Fix/#97] 카카오 로그인 리다이렉트 url 변경
  src/main/resources/application.yml
Labels: fix
